<a href="https://colab.research.google.com/github/sepehriravani/explainable-predictive-maintenance/blob/main/notebooks/02_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Explainable Predictive Maintenance

## 02 — Data Preprocessing

In this notebook, I prepare the dataset for machine learning.

In [ ]:
!pip install -q ucimlrepo

In [ ]:
from ucimlrepo import fetch_ucirepo

In [ ]:
data = fetch_ucirepo(id=601)

X = data.data.features
y = data.data.targets

In [ ]:
target = y["Machine failure"]

In [ ]:
df = X.copy()
df["Machine failure"] = target

In [ ]:
df.head()

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Machine failure
0,M,298.1,308.6,1551,42.8,0,0
1,L,298.2,308.7,1408,46.3,3,0
2,L,298.1,308.5,1498,49.4,5,0
3,L,298.2,308.6,1433,39.5,7,0
4,L,298.2,308.7,1408,40.0,9,0

In [ ]:
features = df.drop("Machine failure", axis=1)
target = df["Machine failure"]

In [ ]:
features.head()

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear
0,M,298.1,308.6,1551,42.8,0
1,L,298.2,308.7,1408,46.3,3
2,L,298.1,308.5,1498,49.4,5
3,L,298.2,308.6,1433,39.5,7
4,L,298.2,308.7,1408,40.0,9

In [ ]:
import pandas as pd

In [ ]:
features_encoded = pd.get_dummies(
    features,
    columns=["Type"],
    dtype=int
)

In [ ]:
features_encoded.head()

,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Type_H,Type_L,Type_M
0,298.1,308.6,1551,42.8,0,0,0,1
1,298.2,308.7,1408,46.3,3,0,1,0
2,298.1,308.5,1498,49.4,5,0,1,0
3,298.2,308.6,1433,39.5,7,0,1,0
4,298.2,308.7,1408,40.0,9,0,1,0

In [ ]:
features_encoded.columns

Index(['Air temperature', 'Process temperature', 'Rotational speed', 'Torque',
       'Tool wear', 'Type_H', 'Type_L', 'Type_M'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    features_encoded,
    target,
    test_size=0.2,
    random_state=42,
    stratify=target
)

In [ ]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (8000, 8)
X_test shape: (2000, 8)
y_train shape: (8000,)
y_test shape: (2000,)

In [ ]:
print("Train failure rate:")
print(y_train.value_counts(normalize=True) * 100)

print("\nTest failure rate:")
print(y_test.value_counts(normalize=True) * 100)

Train failure rate:
Machine failure
0    96.6125
1     3.3875
Name: proportion, dtype: float64

Test failure rate:
Machine failure
0    96.6
1     3.4
Name: proportion, dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
numeric_columns = [
    "Air temperature",
    "Process temperature",
    "Rotational speed",
    "Torque",
    "Tool wear"
]

In [ ]:
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

In [ ]:
scaler = StandardScaler()

X_train_scaled[numeric_columns] = scaler.fit_transform(
    X_train[numeric_columns]
)

In [ ]:
X_test_scaled[numeric_columns] = scaler.transform(
    X_test[numeric_columns]
)

In [ ]:
X_train_scaled[numeric_columns].describe().round(2)

,Air temperature,Process temperature,Rotational speed,Torque,Tool wear
count,8000.00,8000.00,8000.00,8000.00,8000.00
mean,0.00,0.00,0.00,-0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00
min,-2.36,-2.91,-2.05,-3.61,-1.69
25%,-0.85,-0.82,-0.65,-0.68,-0.86
50%,0.05,0.06,-0.20,0.01,-0.01
75%,0.75,0.74,0.41,0.68,0.87
max,2.25,2.56,7.44,3.65,2.28